# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Example Site"
weight = 2

[zh]
languageName = "简体中文"
languagedirection = "ltr"
title = "我的博客"
weight = 1